# -*- mode: ruby -*-
# vi: set ft=ruby :

# This is an IP address of the linux router.
# Change this to fit your local environment.
local_ip = "192.168.10.100"

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-8.3"

  config.vm.define "router" do |r|
    r.vm.provider "virtualbox" do |vb|
      vb.name = "lr-router"
    end
    r.vm.hostname = "router"
    # enable ipv4 routing and make it persistent
    r.vm.provision "shell", inline: <<-SHELL
      echo 1 > /proc/sys/net/ipv4/ip_forward
      echo net.ipv4.ip_forward = 1 > /etc/sysctl.d/ip_forward.conf
    SHELL
    r.vm.network "public_network", ip: local_ip
    r.vm.network "private_network", ip: "10.1.1.10",
      virtualbox__intnet: "intnet1"
    r.vm.network "private_network", ip: "10.5.5.10", 
      virtualbox__intnet: "intnet2"
  end


  (1..2).each do |i|
    config.vm.define "node1-#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "lr-node1-#{i}"
      end
      node.vm.hostname = "node1-#{i}"
      node.vm.network "private_network", ip: "10.1.1.2#{i-1}",
        virtualbox__intnet: "intnet1"
    end
  end

  (1..2).each do |i|
    config.vm.define "node2-#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "lr-node2-#{i}"
      end
      node.vm.hostname = "node2-#{i}"
      node.vm.network "private_network", ip: "10.5.5.2#{i-1}",
        virtualbox__intnet: "intnet2"
    end
  end

  # add some packages and disable default gateway and DNS 
  # settings on all the VMs
  config.vm.provision "shell", inline: <<-SHELL
    dnf install vim bash-completion -y
    nmcli con mod eth0 ipv4.never-default yes
    nmcli con mod eth0 ipv4.ignore-auto-dns yes
    nmcli con up eth0
  SHELL

end