# -*- mode: ruby -*-
# vi: set ft=ruby :

# change these two variables to match your environment
ifname = "VirtualBox Host-Only Ethernet Adapter"
nw_portion = "192.168.220"

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-8.3"

  config.vm.define "kea" do |kea|
    kea.vm.provider "virtualbox" do |vb|
      vb.name = "d2-kea"
    end
    kea.vm.hostname = "dhcp1.example.com"
    kea.vm.network "private_network", ip: "#{nw_portion}.10", name: ifname
    # Install Kea DHCP server and other utilities
    kea.vm.provision "shell", inline: <<-SHELL
      dnf install bash-completion vim wireshark-cli epel-release -y
      usermod -aG wireshark vagrant
      curl -1sLf \
      'https://dl.cloudsmith.io/public/isc/kea-1-8/cfg/setup/bash.rpm.sh' | bash
      dnf install isc-kea -y
      for i in kea-dhcp4 kea-dhcp-ddns; do
        mv /etc/kea/$i.conf /etc/kea/$i.conf.bak
        cp /vagrant/config/dhcp/$i.conf /etc/kea/
        chmod 644 /etc/kea/$i.conf
        systemctl enable $i ; systemctl start $i
      done
    SHELL
  end

  config.vm.define "bind" do |bind|
    bind.vm.provider "virtualbox" do |vb|
      vb.name = "d2-bind"
    end
    bind.vm.hostname = "ns1.example.com"
    bind.vm.network "private_network", ip: "#{nw_portion}.11", name: ifname
    bind.vm.provision "shell", inline: <<-SHELL
      dnf install bash-completion vim wireshark-cli bind bind-utils -y
      usermod -aG wireshark vagrant
      mv /etc/named.conf /etc/named.conf.bak
      cp /vagrant/config/dns/named.conf /etc
      chown root:named /etc/named.conf
      chmod 640 /etc/named.conf
      cp -r /vagrant/config/dns/zones /etc/named
      chown -R root:named /etc/named/zones
      chmod 750 /etc/named/zones
      chmod 660 /etc/named/zones/*
      systemctl enable named ; systemctl start named
    SHELL
  end

  config.vm.define "router" do |r|
    r.vm.provider "virtualbox" do |vb|
      vb.name = "d2-router"
    end
    r.vm.hostname = "dfg.example.com"
    # enable ipv4 routing and make it persistent
    r.vm.provision "shell", inline: <<-SHELL
      echo 1 > /proc/sys/net/ipv4/ip_forward
      echo net.ipv4.ip_forward = 1 > /etc/sysctl.d/ip_forward.conf
      systemctl enable firewalld ; systemctl start firewalld
      firewall-cmd --zone=external --change-interface=eth0
      firewall-cmd --runtime-to-permanent
    SHELL
    r.vm.network "private_network", ip: "#{nw_portion}.5", name: ifname
  end

  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "d2-node#{i}"
      end
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network "private_network", type: "dhcp", name: ifname
      # Vagrant uses eth0 with NAT as a default gateway, but we want to 
      # disable this behavior.
      node.vm.provision "shell", inline: <<-SHELL
        dnf install bash-completion bind-utils -y
        nmcli con mod eth0 ipv4.never-default yes
        nmcli con mod eth0 ipv4.ignore-auto-dns yes
        nmcli con up eth0
      SHELL
    end
  end

end